#!/bin/bash

SOUNDTOUCH_API="http://soundtouch.local:8090"

for PRESET_ID in {1..6}
do
  echo "Store preset ${PRESET_ID}..."
  PRESET_XML="
  <preset id=\"${PRESET_ID}\">
    <ContentItem source=\"LOCAL_INTERNET_RADIO\" type=\"stationurl\" location=\"https://gmuth.github.io/presets/${PRESET_ID}.json\">
      <itemName>loading github preset ${PRESET_ID}.json</itemName>
    </ContentItem>
  </preset>"
  echo $PRESET_XML | curl -sfd @- $SOUNDTOUCH_API/storePreset >/dev/null || echo "Failed to store preset ${PRESET_ID}"
done

curl -s $SOUNDTOUCH_API/presets | xmllint --format -